FriendlyErrorNames.resx
=> CP-10833: Update licensing text

FriendlyErrorNames.resx
-Updated FriendlyErrorNames.resx
=> CA-157503 and CP-11764

FriendlyErrorNames.resx
Updated PATCH_PRECHECK_FAILED_WRONG_SERVER_VERSION
=> CA-111770 

java/main.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
=> Import is a reserved word in Java

FriendlyErrorNames.resx
-  changed the message for SR_ATTACHED_ON_SLAVE
=> CP-14649: Add friendly names for new PBD API errors

FriendlyErrorNames.resx
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>
=> CP-15398: Make friendly error message unbranded

c/helper.ml
This PR needs to go in at the same time as we switch to ocaml-4.02 in trunk-ring3.
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
=> Fix build with ocaml 4.02

FriendlyErrorNames.resx
- changed some error messages and removed SR_ATTACHED_ON_SLAVE, which has been removed from xapi
=> CA-202310: Update friendly error names

FriendlyErrorNames.resx
=> CA-204254: Remove xenprep error from FriendlyErrorNames

csharp/src/HTTP.cs
Signed-off-by: Frederico Mazzone <fredericom@drall.uk.xensource.com>
=> CP-17231: Implemented proxy authentication in C# SDK

c/gen_c_binding.ml, c/helper.ml, csharp/gen_csharp_binding.ml, friendly_error_names.ml, java/main.ml, powershell/common_functions.ml, powershell/gen_powershell_binding.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
=> Use stdext 2.0.0

c/OMakefile, c/test/test_vm_async_migrate.c, csharp/gen_csharp_binding.ml
Also, minor code simplification.
=> Do not generate object download methods for releases above boston.

csharp/src/HTTP.cs
Reverts xapi-project/xen-api-sdk#70
=> Revert "CP-17231: Implemented proxy authentication in C# SDK"

csharp/src/HTTP.cs
Signed-off-by: Frezzle <frederico.mazzone@citrix.com>
=> CP-19111: Added ability to choose Basic or Digest authentication for proxy server

powershell/about_XenServer.help.txt
=> Removed bytes that appeared as double dash on windows.

OMakefile, mk/Makefile
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
=> Use the xapi-datamodel ocamlfind package rather than path/to/cmxa

csharp/src/HTTP.cs
Signed-off-by: Frederico Mazzone <frederico.mazzone@citrix.com>
=> Don't expose utility function in API

FriendlyErrorNames.resx
=> CA-241725: Better FriendlyErrorName for UPDATE_APPLY_FAILED

c/OMakefile, c/xen_common.c, c/xen_common.h, csharp/src/Helper.cs, java/lib/com/xensource/xenapi/APIVersion.java
=> Bumped the API version to 2.7.

csharp/src/HTTP.cs
This is needed because the move operation might fail if there is an anti-virus running on the machine (we are doing the move immediately after we finished writing the file and the anti-virus software might be checking the file at that point)
=> CA-249845: Add a retry mechanism around File.Move in the GET function

.travis.yml, README.md, opam
I'll add a `.merlin` file in a separate PR, as it's not strictly related
=> Add opam file & Travis configuration

Makefile, csharp/gen_csharp_binding.ml
=> Stop generating two almost identical versions of the C# SDK.

csharp/FriendlyErrorNames.resx
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>
=> CA-187179: Add AUTH_DISABLE_FAILED_INVALID_ACCOUNT error message

java/lib/Makefile.dist, java/lib/com/xensource/xenapi/Connection.java
This PR is mainly aimed at the UI-SDK team (but anyone is welcome to comment).
The commits are best reviewed separately. The first and third commits are the minimum fix for CA-260203 and have been separated in case we need to backport it to older branches. The second commit is an improved fix for use on master only and the fourth one removes some code that was deprecated ages ago.
=> Java SDK: CA-260203 plus some maintenance

powershell/gen_powershell_binding.ml, powershell/src/Connect-XenServer.cs
This PR contains some PS module enhancements; the changes are in PS's C# source code.
=> CA-249080, CA-109372, CP-4751

.travis.yml, xen-api-sdk.opam
This should speed up our Travis builds significantly.
=> Fix Travis build and remove unnecessary dependency on xapi

common/CommonFunctions.ml, csharp/gen_csharp_binding.ml, csharp/src/Converters.cs, csharp/src/Event.cs, csharp/src/EventHelpers.cs, csharp/src/HTTP.cs, csharp/src/JsonRpc.cs, csharp/src/Session.cs, csharp/src/XenObject.cs, csharp/templates/XenServer.csproj.mustache, powershell/common_functions.ml
I am resubmitting this to a different branch.
=> CP-21739: Added support for the JsonRpc protocol in the C# SDK.

csharp/samples/Program.cs, csharp/samples/Properties/AssemblyInfo.cs
=> Namespace and assembly metadata correction.

.travis.yml
Please only merge this if travis goes green.
=> Futher attempt to fix travis.

csharp/src/Session.cs
For C# audience only. Best review the commits one by one.
=> CA-275566 plus refactoring.

Makefile, c/gen_c_binding.ml, c/helper.ml, c/jbuild, common/CommonFunctions.ml, common/jbuild, csharp/gen_csharp_binding.ml, csharp/jbuild, java/jbuild, java/main.ml, powershell/common_functions.ml, powershell/gen_powershell_binding.ml, powershell/jbuild, xen-api-sdk.opam
Plus: Makefile improvement; warning fix.
=>  Changed dependencies to use the newly defined packages.

csharp/gen_csharp_binding.ml, csharp/src/Converters.cs
Added check to catch new types of maps not covered. Corrections to converters.
=> CA-283613: Added missing converters for Map(Ref,Int) and Map(Ref,Map(String,String)).

c/README.dist, c/gen_c_binding.ml, csharp/gen_csharp_binding.ml, csharp/src/JsonRpc.cs, java/main.ml
This is @kc284 's work on supporting the datamodel option type in the SDK.
This has to be merged together with the corresponding PR in XAPI:
https://github.com/xapi-project/xen-api/pull/3544
See internal jenkins build on feature/REQ477/probe builds 66 and 72 that have successfully built the rpms and the SDK.
=> [477 merge] CP-27391: datamodel option type support

c/gen_c_binding.ml, csharp/gen_csharp_binding.ml, csharp/src/Session.cs, java/samples/EventMonitor.java, java/samples/TestBase.java, java/templates/GetAllRecordsOfAllTypes.mustache, powershell/gen_powershell_binding.ml
Commits best reviewed separately.
=>  CA-286574; java test update; other minor corrections; indentation.

csharp/templates/XenServer.csproj.mustache
=> Remove EventHelpers file from the XenServer project file

powershell/common_functions.ml
Signed-off-by: Ming Lu <ming.lu@citrix.com>
=> Remove renaming from url to Url_ in powershell bindings
