- csharp/gen_csharp_binding.ml
This field was recently added to Datamodel_types in the xen-api repo.
Signed-off-by: Rob Hoes <rob.hoes@citrix.com>
> Make csharp bindings aware of new msg_doc_tags field

- csharp/gen_csharp_binding.ml
- powershell/common_functions.ml
First part of a fix.
The work for CP-11136 in xen-api added a field of type Set(Int)
to the Host, to hold the set of Virtual Hardware Platform
Versions that it offers. The "exposed_type" functions here in
the SDK generation code did not handle Set(Int) but threw an
assertion error.  Now they return "long[]".
Still to do: handle Set(Int) in the functions
simple_convert_from_proxy and convert_to_proxy in
csharp/gen_csharp_binding.ml
Signed-off-by: Thomas Sanders <thomas.sanders@citrix.com>
> CP-11136: Handle Set(Int) in "exposed_type" functions.

- csharp/gen_csharp_binding.ml
- powershell/common_functions.ml
I had done part of the work to handle Set(Int) and then JonL did a
complete job on a different branch; when his changes were ported to
here they clashed with my change.
Signed-off-by: Thomas Sanders <thomas.sanders@citrix.com>
> Fix duplicated Set(Int) in two matches.

- csharp/gen_csharp_binding.ml
This avoids needing to patch the C# code generator whenever the
`message` record is expanded.
This needs to be merged at the same time as [xapi-project/xen-api#2354]
> CP-12901: use a pre-populated `message` type

- csharp/src/XenServer.csproj.header
- mk/Makefile
- mk/csharp.sh
- mk/powershell.sh
- mk/sign-ps.bat
- powershell/XenServerPSModule.psd1
- powershell/src/Connect-XenServer.cs
This pull request is upgrading the C# SDK to use .net 4.5 as well as making the necessary changes in the PowerShell module
> CP-13394: Build DotNetPackages & C# SDK with .NET 4.5

- powershell/src/Connect-XenServer.cs
Modified the PowerShell SDK to call the newest overload of login_with_password XAPI call where the originator field is specified.
Signed-off-by: Gabor Apati-Nagy <gabor.apati-nagy@citrix.com>
> CP-9891: SDK: "originator" param for xapi login_with_password (CI-44)

- FriendlyErrorNames.resx
Fixed the usage of 'username' and 'user name' in FriendlyErrorNames
Signed-off-by: Gabor Apati-Nagy <gabor.apati-nagy@citrix.com>
> CA-211363: Replace 'User name' labels with 'Username'

- csharp/src/HTTP.cs
Improved the ReadHttpHeaders function, by making sure that a chunk is read fully from the stream (the number of bytes read by the Stream.Read function can be less than the number of bytes requested, so we need to continue reading until the required number of bytes is read)
> CA-242397: Fix format exception caused by incorrect  chunk reading

- csharp/src/HTTP.cs
This is needed because the move operation might fail if there is an anti-virus running on the machine (we are doing the move immediately after we finished writing the file and the anti-virus software might be checking the file at that point)
> Cherry-picking CA-249845: Add a retry mechanism around File.Move in the GET function

- csharp/FriendlyErrorNames.resx
This is another part of pull request on xenserver/xenadmin.
https://github.com/xenserver/xenadmin/pull/1668
Both of them are for a new error message: POOL_AUTH_ENABLE_FAILED_INVALID_ACCOUNT
> CA-254480: XenCenter error message refine for CA-205515

- c/gen_c_binding.ml
- c/helper.ml
- common/CommonFunctions.ml
- common/licence.ml
- csharp/friendly_error_names.ml
- csharp/gen_csharp_binding.ml
- java/main.ml
- powershell/common_functions.ml
- powershell/gen_powershell_binding.ml
It's easier if the commits are reviewed separately as the first one is loads of whitespace.
The second one restores in the autogenerated output the broken `Get-XenMessage` and removes completely the empty `Get-Xen<T> where T: Auth, DataSource, LVHD, User, VTPM`.
> CA-125488, CA-212616, plus ocp-indentation.

- c/gen_c_binding.ml
- csharp/gen_csharp_binding.ml
- java/main.ml
- powershell/common_functions.ml
- powershell/gen_powershell_binding.ml
Commit 3494cda409dd7529c02ce599cda60300f18c7ea1 in xen-api.git
introduced a change to the Enum data constructor, which now takes 3
arguments. This requires changing it here. The new argument is simply
being ignored.
Signed-off-by: Christian Lindig <christian.lindig@citrix.com>
> CP-24819 Enum now has 3 arguments

- c/gen_c_binding.ml
- csharp/gen_csharp_binding.ml
- java/main.ml
- powershell/common_functions.ml
- powershell/gen_powershell_binding.ml
This requires more changes because the compilation triggered by the
build-before.sh script breaks.
This reverts commit 66eda99294777d91989acd8f14120f8ea2e6b542.
> Revert "CP-24819 Enum now has 3 arguments"

- powershell/gen_powershell_binding.ml
The problem was in New-XenClusterHost.cs, we had the following code
generated:
```
[Parameter(ParameterSetName = "Fields")]
public XenRef<XenAPI.Cluster> Cluster { get; set; }
[Parameter(ParameterSetName = "Fields")]
public XenRef<XenAPI.Host> XenHost { get; set; }
...
if (Record != null)
{
Cluster = Record.cluster;
Host = Record.host;
}
```
where Cluster was being set correctly, but it was trying to assign
to Host rather than XenHost. The Hashtbl implementation slightly
further on was correct:
```
Cluster = Marshalling.ParseRef<Cluster>(HashTable, "cluster");
XenHost = Marshalling.ParseRef<Host>(HashTable, "host");
```
The fix it to use the code used in the Hashtbl part, which is a
call to `ocaml_class_to_csharp_property x` rather than
`exposed_class_name (pascal_case x)`. Turns out the …
> CA-267461: Fix powershell bindings generator for some constructors

- csharp/gen_csharp_binding.ml
- csharp/src/Event.cs
- csharp/src/Session.cs
- powershell/src/Connect-XenServer.cs
Use the opaque_ref so it's obvious what it is. Although sessions do have uuids,
we can't simply change it to its real value given it is such a central concept,
hence it's better to deprecate it.
> CA-40854: The Session's uuid is in reality its opaque_ref.

- python/samples/shutdown.py
This script provides functions for shutting down VMs under different conditions,
and was previously included with xapi until OCaml code was added serving the same purpose.
Signed-off-by: Akanksha Mathur <akanksha.mathur@citrix.com>
> CA-285349: Add shutdown.py as example script

- c/helper.ml
This integrates a patch that was applied during the build process.
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
> helpers: Add out_indent for compat with ocaml 4.06

- csharp/autogen/src/Session.cs
Also, removed unused private static constructor.
> CA-311238 refix: when creating a session from another Session object, copy over its properties.

- .travis.yml
I see that one of the travis builds keeps failing (and the one with allowed failure passing): https://travis-ci.org/xapi-project/xen-api-sdk/builds/547159404
Use just one remote, and use an https URL.
opam update seems to fail with a git URL.
> Simplify Travis setup

- .travis.yml
This allows the SDK to automatically get build with up-to-date ci settings
> travis: pull settings from xs-opam

- c/gen_c_binding.ml
- csharp/gen_csharp_binding.ml
- java/main.ml
- powershell/common_functions.ml
- powershell/gen_powershell_binding.ml
The difference between these only matter for XAPI's implementation,
not the clients.
> CA-333712: handle wrapped strings the same as strings

- powershell/about_XenServer.help.txt
- powershell/autogen/samples/AutomatedTestCore.ps1
- powershell/autogen/samples/HttpTest.ps1
- powershell/gen_powershell_binding.ml
See commit messages for details. Commits best reviewed separately.
> CA-340392 + minor script corrections

- csharp/FriendlyErrorNames.resx
Please review but do not merge before this PR https://github.com/xapi-project/xen-api/pull/4157 hits master.
> Removed error message override because it has been outdated by the original API error message.

- csharp/autogen/src/HTTP.cs
- csharp/gen_csharp_binding.ml
- csharp/templates/HTTP_actions.mustache
- powershell/autogen/src/Receive-XenPoolPatch.cs
- powershell/autogen/src/Send-XenOemPatchStream.cs
- powershell/gen_powershell_binding.ml
- powershell/templates/XenServerPowerShell.csproj.mustache
CA-345342: Made the query parameters of the http actions optional using as default value the type default.
Note that some of them are not optional, however, the current definition does not allow for distinguishing them from the mandatory ones, and as a consequence it is easier to mark them all as optional than provide method overloads manually.
Also, exposed manually in the SDK http actions removed from the API.
Use a mustache template to generate the HTTP actions.
> CA-345342: Made the query parameters of the http actions optional
